<?php
/**
 * Thankyou page
 *
 * @author 		WooThemes
 * @package 	WooCommerce/Templates
 * @version     2.0.0
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $woocommerce;

if ( $order ) : ?>

	<?php if ( in_array( $order->status, array( 'failed' ) ) ) : ?>

		<p><?php _e( 'Unfortunately your order cannot be processed as the originating bank/merchant has declined your transaction.', 'woocommerce' ); ?></p>

		<p><?php
			if ( is_user_logged_in() )
				_e( 'Please attempt your purchase again or go to your account page.', 'woocommerce' );
			else
				_e( 'Please attempt your purchase again.', 'woocommerce' );
		?></p>

		<p>
			<a href="<?php echo esc_url( $order->get_checkout_payment_url() ); ?>" class="button pay d_align"><?php _e( 'Pay', 'woocommerce' ) ?></a>
			<?php if ( is_user_logged_in() ) : ?>
			<a href="<?php echo esc_url( get_permalink( woocommerce_get_page_id( 'myaccount' ) ) ); ?>" class="button pay d_align"><?php _e( 'My Account', 'woocommerce' ); ?></a>
			<?php endif; ?>
                        <div class="clear"></div>
		</p>

	<?php else : ?>
	
		<p><?php _e( 'Thank you. Your order has been received.', 'woocommerce' ); ?></p>
		<?php //do_action( 'woocommerce_after_checkout_validation' )?>
		<ul class="order_details">
			<li class="order">
				<?php _e( 'Order:', 'woocommerce' ); ?>
				<strong><?php echo $order->get_order_number() ?></strong>
			</li>
			<li class="date">
				<?php _e( 'Date:', 'woocommerce' ); ?>
				<strong><?php echo date_i18n( get_option( 'date_format' ), strtotime( $order->order_date ) ); ?></strong>
			</li>
			<li class="total">
				<?php _e( 'Total:', 'woocommerce' ); ?>
				<strong><?php echo $order->get_formatted_order_total(); ?></strong>
			</li>
			<?php if ( $order->payment_method_title ) : ?>
			<li class="method">
				<?php _e( 'Payment method:', 'woocommerce' ); ?>
				<strong><?php echo $order->payment_method_title; ?></strong>
			</li>
			<?php endif; ?>
			
		</ul>
                
                	<p>	
			<?php 
			/**
			 * Show Package Number as fetched from cargonizer and stored as order custom field.
			 * If it's generated by "Small Packages" shipping option then a text is displayed
			 */
                        
                        /*
                        
			$package_number = get_post_meta( $order->id, 'Package Number', true );
			if ($package_number == "Small Packages Shipping Option"){
				$package_number = __( "The package is sent as ordinary letter and is received within 1-2 weekdays", "theretailer" );
			}
			_e( 'Package Number:', 'theretailer' ); echo "&nbsp;<b><a href='http://sporing.posten.no/sporing.html?q=$package_number&lang=no' target='_blank'>" . $package_number . "</a></b>";                          
                         */
			?>
			<?php do_action( 'woocommerce_special_thankyou_' . $order->payment_method, $order->id );?>
			</p>
			
			
		
		<div class="clear"></div>

	<?php endif; ?>
	<?php 
		if ($order->payment_method == 'bacs'){
			_e( 'Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order wont be shipped until the funds have cleared in our account.', 'woocommerce' );
		}
	?>
	<?php //do_action( 'woocommerce_special_thankyou_' . $order->payment_method, $order->id ); ?>
	<?php //do_action( 'woocommerce_thankyou_' . $order->payment_method, $order->id ); ?>
	<?php do_action( 'woocommerce_thankyou', $order->id ); ?>

<?php else : ?>

	<p><?php _e( 'Thank you. Your order has been received.', 'woocommerce' ); ?></p>

<?php endif; ?>
